# Script 16: Auto-Update Website Data
#
# This script reads the latest predictions from CSV and writes them
# as a JS file the website loads. Run this every time you want to
# update the live site with fresh predictions.
#
# Usage: Just run this script after updating predictions.

rm(list = ls())

cat("=== UPDATING WEBSITE WITH LATEST PREDICTIONS ===\n\n")

# Load latest predictions
preds <- read.csv("data/unified_predictions.csv", stringsAsFactors=FALSE)
next_mw <- preds[preds$MatchweekEst == 1, ]

cat("Loaded", nrow(preds), "total predictions\n")
cat("Next matchweek:", nrow(next_mw), "matches\n\n")

# Get high confidence picks across ALL remaining matches
high_conf <- preds[preds$Confidence >= 50 & preds$BothAgree, ]
high_conf <- high_conf[order(-high_conf$Confidence), ]

cat("High confidence picks:", nrow(high_conf), "\n\n")


# Build the JS file
js_lines <- c(
  "// Auto-generated by scripts/16_update_website.R",
  paste0("// Generated: ", format(Sys.time(), "%Y-%m-%d %H:%M")),
  paste0("// Total predictions: ", nrow(preds)),
  "",
  "const weeklyMatches = ["
)

# Next matchweek matches
for (i in 1:nrow(next_mw)) {
  r <- next_mw[i,]
  rain_str   <- if(isTRUE(r$RainWarning)) ", rain: true" else ""
  stakes_str <- if(isTRUE(r$Importance > 0.6)) ", highStakes: true" else ""
  agree_str  <- paste0(", bothAgree: ", tolower(as.character(r$BothAgree)))

  comma <- if(i < nrow(next_mw)) "," else ""
  js_lines <- c(js_lines, sprintf(
    '  { home: "%s", away: "%s", predResult: "%s", confidence: %d, probHome: %.1f, probDraw: %.1f, probAway: %.1f, expHome: %.1f, expAway: %.1f%s%s%s }%s',
    r$HomeTeam, r$AwayTeam, r$PredResult, r$Confidence,
    r$ProbHome, r$ProbDraw, r$ProbAway, r$ExpHome, r$ExpAway,
    rain_str, stakes_str, agree_str, comma
  ))
}
js_lines <- c(js_lines, "];", "")

# High confidence picks
js_lines <- c(js_lines, "const highConfPicks = [")
for (i in 1:nrow(high_conf)) {
  r <- high_conf[i,]
  rain_str   <- if(isTRUE(r$RainWarning)) ", rain: true" else ", rain: false"
  stakes_str <- if(isTRUE(r$Importance > 0.6)) ", highStakes: true" else ", highStakes: false"

  comma <- if(i < nrow(high_conf)) "," else ""
  js_lines <- c(js_lines, sprintf(
    '  { home: "%s", away: "%s", predResult: "%s", confidence: %d, bothAgree: true%s%s }%s',
    r$HomeTeam, r$AwayTeam, r$PredResult, r$Confidence,
    rain_str, stakes_str, comma
  ))
}
js_lines <- c(js_lines, "];", "")

# Write JS file
writeLines(js_lines, "predictions.js")
cat("✓ predictions.js created\n\n")
